# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feb0d76b8c6dd98ab769f42a9b48051ee84af8b4f57805857528cb39d13bae29947ad06061e40a9b14fabe451eba74fb7f3dfc6886548febb76ba6d1556db0c6

test:
  secret_key_base: 6ebc7f9b283d132ec61f540e5513f6cbd2a4cd398fcb81627ab6eadd07145257d0b1b4c716e58231302a8d476180e5c3d8d896345fa8b4f6f67d135ddd329c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
